package exception.wrapper;

public class Util {

  public static int doubleTimes(int i) throws Exception {
    return i * 2;
  }
}
